# Generated by Django 5.0.2 on 2026-06-06 08:49

import djmoney.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='currency',
        ),
        migrations.AddField(
            model_name='subscription',
            name='price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'Euro'), ('PLN', 'Polish Zloty'), ('USD', 'US Dollar')], default='PLN', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, max_digits=14),
        ),
    ]
